// Utility functions for displaying artist and style information in a user-friendly way

export function formatArtistName(artistKey: string): string {
  // Convert camelCase or snake_case to proper names
  const nameMap: Record<string, string> = {
    'picasso': 'Pablo Picasso',
    'vangogh': 'Vincent van Gogh',
    'monet': 'Claude Monet',
    'matisse': 'Henri Matisse',
    'klimt': 'Gustav Klimt',
    'munch': 'Edvard Munch',
    'dali': 'Salvador Dalí',
    'bacon': 'Francis Bacon',
    'mucha': 'Alphonse Mucha',
    'hokusai': 'Hokusai',
    'warhol': 'Andy Warhol',
    'basquiat': 'Jean-Michel Basquiat',
    'caravaggio': 'Caravaggio',
    'rembrandt': 'Rembrandt',
    'bosch': 'Hieronymus Bosch',
    'mondrian': 'Piet Mondrian',
    'pollock': 'Jackson Pollock',
    'miro': 'Joan Miró',
    'lichtenstein': 'Roy Lichtenstein',
    'haring': 'Keith Haring',
    // Added Renaissance
    'davinci': 'Leonardo da Vinci',
    'botticelli': 'Sandro Botticelli',
    'giotto': 'Giotto',
    // Children’s/Illustration & style-first labels
    'alice_tenniel': 'Alice in Wonderland (John Tenniel)',
    'dr_seuss': 'Dr. Seuss',
    'maurice_sendak': 'Maurice Sendak',
    'quentin_blake': 'Quentin Blake',
    'mary_blair': 'Mary Blair',
    'winnie_pooh_shepard': 'Winnie-the-Pooh (E. H. Shepard)',
    'mary_poppins_shepard': 'Mary Poppins (Mary Shepard)',
    'fairy_tales_rackham': 'Fairy Tales (Arthur Rackham)',
    'fairy_tales_kay_nielsen': 'Fairy Tales (Kay Nielsen)',
    'madeline_bemelmans': 'Madeline (Ludwig Bemelmans)',
    'charlottes_web_williams': "Charlotte's Web (Garth Williams)",
    'moomins_jansson': 'Moomins (Tove Jansson)',
    'jan_brett': 'Nordic Folk Borders (Jan Brett)',
    'shel_silverstein': 'Shel Silverstein',
    'eric_carle': 'Eric Carle',
    'beatrix_potter': 'Beatrix Potter',
  }

  if (nameMap[artistKey]) return nameMap[artistKey]
  // Fallbacks: convert snake_case or camelCase to Title Case
  if (artistKey.includes('_')) {
    return artistKey
      .split('_')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ')
  }
  return artistKey.replace(/([A-Z])/g, ' $1').replace(/^\w/, (c) => c.toUpperCase()).trim()
}

export function formatStyleName(styleKey: string): string {
  if (styleKey === 'custom_reference') {
    return 'Custom Reference'
  }
  
  // Convert snake_case to proper names
  const styleMap: Record<string, string> = {
    'blue_period': 'Blue Period',
    'rose_period': 'Rose Period',
    'analytical_cubism': 'Analytical Cubism',
    'synthetic_cubism': 'Synthetic Cubism',
    'line_sketch': 'Line Sketch',
    'scream': 'The Scream Style',
    'symbolist': 'Symbolist Phase',
    'frieze': 'Frieze of Life',
    'late_impressionism': 'Late Impressionism',
    'woodcuts': 'Woodcuts & Lithographs',
    'classic_surrealism': 'Classic Surrealism',
    'paranoiac': 'Paranoiac-Critical Method',
    'religious_mythic': 'Religious/Mythic Phase',
    'animal_hybrids': 'Animal Hybrids',
    'hyperrealist': 'Hyperrealist Surrealism',
    'starry_night': 'Starry Night Style',
    'sunflowers': 'Sunflowers/Still Lifes',
    'arles_portraits': 'Arles Portraits',
    'early_dutch': 'Early Dutch Phase',
    'japanese': 'Japanese-Inspired',
    'fauvism': 'Fauvism',
    'interiors': 'Decorative Interiors',
    'simplified_portraits': 'Simplified Portraits',
    'cutouts': 'Cut-outs',
    'golden': 'Golden Phase',
    'portraits': 'Portraits',
    'landscapes': 'Landscapes',
    'sketches': 'Sketches',
    'water_lilies': 'Water Lilies',
    'haystacks_cathedral': 'Haystacks/Cathedral Series',
    'urban': 'Urban Impressionism',
    'early_realism': 'Early Realism',
    'screaming_popes': 'Screaming Popes',
    'triptychs': 'Triptychs',
    'distorted_portraits': 'Distorted Portraits',
    'animalistic_abstractions': 'Animalistic Abstractions',
    'posters': 'Posters',
    'seasonal': 'Seasonal Panels',
    'decorative_panels': 'Decorative Panels',
    'lithographs': 'Lithographs',
    'great_wave': 'The Great Wave',
    'mount_fuji': 'Mount Fuji Series',
    'nature_animals': 'Nature & Animals',
    'manga_sketches': 'Manga Sketches',
    'marilyn': 'Marilyn-style Silkscreens',
    'silkscreen_imperfections': 'Silkscreen Imperfections',
    'commercial_flat': 'Commercial Flat',
    'neo_expressionist': 'Neo-expressionist Graffiti',
    'text_symbols': 'Text & Symbols',
    'primitive_figures': 'Primitive Figures',
    'color_block': 'Color-block Compositions',
    'chiaroscuro': 'Chiaroscuro',
    'religious': 'Religious Dramatic Scenes',
    'still_life': 'Still-life Naturalism',
    'portrait_chiaroscuro': 'Portrait Chiaroscuro',
    'self_portrait': 'Self-Portrait Style',
    'etchings': 'Sketch Etchings',
    'hellscapes': 'Fantastical Hellscapes',
    'hybrid_animals': 'Hybrid Animals',
    'surreal_allegories': 'Surreal Allegories',
    'geometric': 'Geometric Abstraction',
    'early_naturalism': 'Early Naturalism',
    'drip': 'Drip Technique',
    'action': 'Action Painting',
    'biomorphic': 'Biomorphic Abstraction',
    'childlike': 'Childlike Primitivism',
    'comic_pop': 'Comic Pop',
    'whaam': 'Whaam!-style',
    'outlined_figures': 'Outlined Figures',
    'motion_lines': 'Motion Lines',
    // New styles (explicit where naming needs polish)
    'victorian_engraving': 'Victorian Engraving',
    'wonderland_ensemble': 'Wonderland Ensemble',
    'cheshire_grin': 'Cheshire Grin',
    'tissue_collage': 'Tissue Collage',
    'simple_animals': 'Simple Animals',
    'watercolor_animals': 'Watercolor Animals',
    'storybook': 'Storybook Vignettes',
    'wild_things': 'Wild Things',
    'storybook_plate': 'Storybook Plate',
    'ink_splash': 'Ink + Splash',
    'chaotic_page': 'Chaotic Page',
    'storybook_fantasia': 'Storybook Fantasia',
    'pen_ink_hatching': 'Pen-and-Ink Hatching',
    'woodland_vignette': 'Woodland Vignette',
    'elegant_ink': 'Elegant Penwork',
    'ink_watercolor_wash': 'Ink + Watercolor Wash',
    'gnarled_forest_plate': 'Gnarled Forest Plate',
    'decorative_plates': 'Decorative Plates',
    'silhouette_scene': 'Silhouette Scene',
    'ink_gouache_paris': 'Ink + Gouache Paris',
    'graphite_realism': 'Graphite Realism',
    'pen_ink_crosshatch': 'Pen-and-Ink Crosshatch',
    'ornate_borders': 'Ornate Borders',
    'minimal_line': 'Minimal Line',
  }
  
  return styleMap[styleKey] || styleKey.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
}
